name: Remove old artifacts
on:
  workflow_dispatch:
  schedule:
    # Every day at 2am
    - cron: '0 2 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: write

    steps:
      - name: Remove old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '1 day'